### ISSUE TITLE
I was unable to automatically resolve your codesigning issue ☹

### ISSUE THREAD

**Issue by AhrimanSefid** [DanTheMan827/ios-app-signer#21]
Hi.
multi Error:

`/var/folders/r4/nykt3h3j6ts74b2960fy4nc00000gn/T/com.DanTheMan827.AppSigner.ZdAF8k3o/out/Payload/PvZ 2.app: invalid resource directory (directory or signature have been modified)
`
Me buy Account Developer.

**Comment by DanTheMan827** [comment]
It could be that PvZ 2 has a Framework that isn't being re-signed properly...

Mind you... the point of this app isn't to pirate App Store apps but rather to sign things like Kodi or emulators so that people without a jailbreak can enjoy them!

It's also useful for developers if they need to change the provisioned devices inside of an IPA and don't want to re-compile from source or don't have the source handy TO re-compile...

**Comment by AhrimanSefid** [comment]
me need make for market ios for iran user.
apple block iran.
plz give me help.

**Comment by bradleyduncan** [comment]
I'm doubtful the developer of this application intends to allow others to illegally gain access to the iOS marketplace. Its for developers to resign applications they've built in Xcode without rebuilding.

**Comment by DanTheMan827** [comment]
@bradleyduncan Couldn't have said it better myself!
