### ISSUE TITLE
mass resign

### ISSUE THREAD

**Issue by kmddd59** [DanTheMan827/ios-app-signer#34]
@DanTheMan827  i have a question about this code i want to sign more than one app at a time is it possible to make it sign all apps in one folder if so how would i go about this?

**Comment by DanTheMan827** [comment]
There is not batch-sign functionality.

**Comment by shusain93** [comment]
I've actually sort of hacked something in that could help you with this. [I made a fork with command line support](https://github.com/shusain93/ios-app-signer). Simply run the app binary with the parameters `-ipa` for your source IPA, `-ipaout` for your output, `-cert` for your certificate name as it appears in the menu choices of the app (VERY IMPORTANT!), and `-profileloc` for the path to your profile. These paths all need to be absolute because while the shell supports `~/Downloads...` apps don't.

You can make a quick bash script to quickly run the command for each one.

**Comment by kmddd59** [comment]
thx will test soon
