### ISSUE TITLE
Can I use it via terminal?

### ISSUE THREAD

**Issue by guillemhs** [DanTheMan827/ios-app-signer#50]
Hello,

I was thinking to sign via command line. I am an automation tester trying to run ipa using Appium (Appium.io)

Is it possible to sign via the command line using ios-app-signer?

**Comment by DanTheMan827** [comment]
My app itself cannot be used with automation.

There is an [old shell script](https://github.com/DanTheMan827/ios-app-signer/tree/shell_script) that I had made before the GUI came about, but I don't know if that would necessarily work either due to the fact that "codesign" is technically a GUI program (for keychain access)

**Comment by Dershowitz011** [comment]
It is not working. It gives the error "Invalid identity" when I try to install on my iPhone THOUGH the identity is valid. The developer identity. Please do tell the command to use with an example, if it works. Thanks.
