### ISSUE TITLE
[enhancement] | Do we have a console application? 

### ISSUE THREAD

**Issue by dannyZhou** [DanTheMan827/ios-app-signer#62]
When we use python or shell etc. we can use console application simply.

**Comment by DanTheMan827** [comment]
The codesign app itself, while a CLI application, technically is still considered a GUI application because it interacts with Keychain.

The app signer actually started out as a shell script, but that hasn't been updated since I made the GUI version, I have no idea if it still works on recent Mac OS versions...

https://github.com/DanTheMan827/ios-app-signer/tree/shell_script

**Comment by dannyZhou** [comment]
Ok Thank you. Closed.
